
# SEO settings
title: "Jefferson"
title2: "Olave" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://heiswayi.github.io/thinkspace # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "hnbloggithub"
twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jefferson"
  job      : "Ingeniero de Sistemas"
  bio      : "Como estudiante universitario, entendí que una de las mejores formas de aprender y afianzar mis conocimientos era explicando lo poco que sé a otros, es así como se me ocurrió crear este blog bajo una filosofía corta pero clara "escribe con el objetivo de ayudar a los demás a solucionar problemas"."
  thumb    : /images/author.jpg
  email    : hnrird@gmail.com
  url      : jeffersonor900.github.io
  github   : jeffersonor900
  twitter  : http://twitter.com/HeiswayiNrird
  facebook : https://www.facebook.com/heiswayi.nrird
  linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
